# Site settings
title: luismiguells # site title
description: My personal webpage
timezone: America/Mexico_City # set your timezone
# image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/luismiguells/luismiguells.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Luis-Miguel López-Santamaría # author name
  bio: Data engineer with 2+ years of experience in machine learning, NLP, and advanced analytics. 
        Skilled in building scalable data solutions, cloud technologies, and systems architecture to drive strategic decision-making 
        and operational efficiency. Proven leader with a background in research on fake news detection and author profiling, 
        passionate about mentoring, cross-functional collaboration, and delivering high-impact results.
  github: luismiguells # github username
  twitter: luismiguells # twitter username
  facebook: facebook_username # facebook username
  email: luis_miguel@outlook.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://luismiguells.github.io" #
baseurl: 
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
